//
//  StoryDetailViewController.swift
//  NYStories
//
//  Created by Maksim Chulkov on 17.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SafariServices

protocol StoryDetailDisplayLogic: AnyObject {

}

class StoryDetailViewController: UIViewController, StoryDetailDisplayLogic {
    var interactor: StoryDetailBusinessLogic?
    var router: StoryDetailRoutingLogic?
    var selectedStory: StoryList.Something.ViewModel.DisplayedStory?
    let storyDetailView = StoryDetailView()

    override func viewDidLoad() {
        super.viewDidLoad()
        self.view.backgroundColor = .white
        view.addSubview(storyDetailView)
        storyDetailView.delegate = self
        setupView()
        displayStoryDetails()
    }

    private func setupView() {
        storyDetailView.translatesAutoresizingMaskIntoConstraints = false
        storyDetailView.topAnchor.constraint(equalTo:view.safeAreaLayoutGuide.topAnchor).isActive = true
        storyDetailView.leftAnchor.constraint(equalTo:view.safeAreaLayoutGuide.leftAnchor).isActive = true
        storyDetailView.rightAnchor.constraint(equalTo:view.safeAreaLayoutGuide.rightAnchor).isActive = true
        storyDetailView.bottomAnchor.constraint(equalTo:view.safeAreaLayoutGuide.bottomAnchor).isActive = true
        
        storyDetailView.setupUI()
    }
    
    func displayStoryDetails() {
        guard let selectedStory = selectedStory else { return }
        self.title = selectedStory.title
        storyDetailView.setup(with: selectedStory)
    }

}

extension StoryDetailViewController: StoryDetailViewProtocol {
    func seeMoreAction() {
        guard let url = selectedStory?.url else { return }
        let config = SFSafariViewController.Configuration()
        config.entersReaderIfAvailable = true
        let vc = SFSafariViewController(url: url, configuration: config)
        self.present(vc, animated: true)
    }
}

extension StoryDetailViewController {
    @objc func goBack() {
        router?.goBack()
    }
}
