//
//  StoryDetailPresenter.swift
//  NYStories
//
//  Created by Maksim Chulkov on 17.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StoryDetailPresentationLogic
{
  func presentSomething(response: StoryDetail.Something.Response)
}

class StoryDetailPresenter: StoryDetailPresentationLogic
{
  weak var viewController: StoryDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: StoryDetail.Something.Response)
  {
    let viewModel = StoryDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
