//
//  StoryDetailViewController.swift
//  NYStories
//
//  Created by Maksim Chulkov on 17.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StoryDetailDisplayLogic: AnyObject
{
    func displaySomething(viewModel: StoryDetail.Something.ViewModel)
}

class StoryDetailViewController: UIViewController, StoryDetailDisplayLogic
{
    var interactor: StoryDetailBusinessLogic?
    var router: StoryDetailRoutingLogic? //(NSObjectProtocol & StoryDetailRoutingLogic & StoryDetailDataPassing)?
    var selectedStory: StoryList.Something.ViewModel.DisplayedStory?
    let storyDetailView = StoryDetailView()
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.view.backgroundColor = .white
        view.addSubview(storyDetailView)
        self.title = "jopa"
        
        setupView()
        doSomething()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    private func setupView() {
        storyDetailView.translatesAutoresizingMaskIntoConstraints = false
        storyDetailView.topAnchor.constraint(equalTo:view.safeAreaLayoutGuide.topAnchor).isActive = true
        storyDetailView.leftAnchor.constraint(equalTo:view.safeAreaLayoutGuide.leftAnchor).isActive = true
        storyDetailView.rightAnchor.constraint(equalTo:view.safeAreaLayoutGuide.rightAnchor).isActive = true
        storyDetailView.bottomAnchor.constraint(equalTo:view.safeAreaLayoutGuide.bottomAnchor).isActive = true
        
        storyDetailView.setupUI()
    }
    
    func doSomething()
    {
        guard let selectedStory = selectedStory else { return }

        storyDetailView.setup(with: selectedStory)
        
//        let request = StoryDetail.Something.Request()
//        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: StoryDetail.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}

extension StoryDetailViewController {
    @objc func goBack() {
        router?.goBack()
    }
}
