//
//  StoryListModels.swift
//  NYStories
//
//  Created by Maksim Chulkov on 17.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum StoryList
{
    // MARK: Use cases
    
    enum Something {
        struct Request {
            
        }
        struct Response {
            var stories: [Story]
        }
        struct ViewModel {
            struct DisplayedStory {
                let image: UIImage
                let title: String
                let author: String
                let description: String
                let url: URL
            }
            var displayedStory: [DisplayedStory]
//            let storyTitle: String
//            let storyAuthor: String
//            let storyImage: UIImage
//            var model: [StoryListTableViewCellModel]
        }
    }
}
