//
//  StoryListRouter.swift
//  NYStories
//
//  Created by Maksim Chulkov on 17.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StoryListRoutingLogic {
    func routeToStoryDetails(story: StoryList.Something.ViewModel.DisplayedStory)
}

class StoryListRouter: StoryListRoutingLogic {
    private weak var viewController: UIViewController?
    
    init(viewController: UIViewController) {
        self.viewController = viewController
    }
    
    func routeToStoryDetails(story: StoryList.Something.ViewModel.DisplayedStory) {
        let builder = StoryDetailBuilder()
        let vc = builder.build(story: story)
        vc.selectedStory = story //This way of data transfering is offered by clean-swift documentation
        self.viewController?.navigationController?.handlePush(vc, animated: true)
    }
}
