//
//  StoryListInteractor.swift
//  NYStories
//
//  Created by Maksim Chulkov on 17.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StoryListBusinessLogic
{
    func fetchStories(request: StoryList.Something.Request)
}

protocol StoryListDataStore
{
    //var name: String { get set }
}

class StoryListInteractor: StoryListBusinessLogic, StoryListDataStore
{
    var presenter: StoryListPresentationLogic?
//    var worker: StoryListWorker?
    var storiesWorker = StoryWorker()
    //var name: String = ""
    
    // MARK: Do something
    
    func fetchStories(request: StoryList.Something.Request) {
//        worker = StoryListWorker() //is essential??
//        worker?.doSomeWork()
        print("fetchStories started")
        storiesWorker.getStoriesList { stories in
            let response = StoryList.Something.Response(stories: stories)
            self.presenter?.presentSomething(response: response)
        }
    }
}
