//
//  StoryListInteractor.swift
//  NYStories
//
//  Created by Maksim Chulkov on 17.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StoryListBusinessLogic {
    func fetchStories(request: StoryList.Something.Request)
}

class StoryListInteractor: StoryListBusinessLogic
{
    var presenter: StoryListPresentationLogic?
    var storiesWorker = StoryWorker()
    
    func fetchStories(request: StoryList.Something.Request) {
        storiesWorker.getStoriesList { stories in
            let response = StoryList.Something.Response(stories: stories)
            self.presenter?.presentModel(response: response)
        }
    }
}
