//
//  StoryListViewController.swift
//  NYStories
//
//  Created by Maksim Chulkov on 17.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StoryListDisplayLogic: AnyObject
{
    func displaySomething(viewModel: StoryList.Something.ViewModel)
}

class StoryListViewController: UIViewController, StoryListDisplayLogic
{
    var interactor: StoryListBusinessLogic?
    var router: StoryListRoutingLogic?//(NSObjectProtocol & StoryListRoutingLogic & StoryListDataPassing)?
    let storyListTableView = StoryListView()

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .white
        view.addSubview(storyListTableView)
        storyListTableView.delegate = self
        setupTableView()
        doSomething()
    }
    
    func doSomething() {
        let request = StoryList.Something.Request()
        interactor?.fetchStories(request: request)
    }
    
    func displaySomething(viewModel: StoryList.Something.ViewModel) {
        storyListTableView.setup(with: viewModel.displayedStory)
    }
    
    private func setupTableView() {
        storyListTableView.translatesAutoresizingMaskIntoConstraints = false
        
        storyListTableView.topAnchor.constraint(equalTo:view.safeAreaLayoutGuide.topAnchor).isActive = true
        storyListTableView.leftAnchor.constraint(equalTo:view.safeAreaLayoutGuide.leftAnchor).isActive = true
        storyListTableView.rightAnchor.constraint(equalTo:view.safeAreaLayoutGuide.rightAnchor).isActive = true
        storyListTableView.bottomAnchor.constraint(equalTo:view.safeAreaLayoutGuide.bottomAnchor).isActive = true
        
        storyListTableView.setupUI()
    }
}

extension StoryListViewController: StoryListViewProtocol {

    func select(model: StoryList.Something.ViewModel.DisplayedStory) {
        print("d")
        router?.routeToStoryDetails(story: model)
        //1. find element in [Story]
        //2. go to StoryDetail with this element
        
    }
}
